[package]
license = "AGPL-3.0-only"
name = "openmat-plot-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
openmat-plot-mir = { path = "../openmat-plot-mir" }
wgpu = { version = "=30.0.1", default-features = false, features = ["std", "parking_lot", "wgsl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "=30.0.1", default-features = false, features = ["dx12", "metal", "vulkan"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "=30.0.1", default-features = false, features = ["webgpu"] }

[lints]
workspace = true
