//! Optional LLVM 22 ORC backend for `OpenMat`'s verified numerical IR.
mod emitter;
mod ffi;

use std::ffi::CStr;
use std::marker::PhantomData;
use std::path::Path;
use std::ptr;
use std::rc::Rc;

use openmat_sim::numeric::{EvalError, KERNEL_ABI_VERSION, Kernel, Program};

pub use emitter::emit_llvm;
use ffi::{Api, Entry, Handle};

struct Jit {
    handle: Handle,
    api: Api,
}

impl Drop for Jit {
    fn drop(&mut self) {
        // SAFETY: This uniquely owned JIT outlives every entry invocation. LLVM
        // remains loaded through the owning Api until disposal has completed.
        let result = unsafe { (self.api.dispose_jit)(self.handle) };
        let _ = self.api.check(result);
    }
}

struct Context<'a> {
    handle: Handle,
    api: &'a Api,
}
impl Drop for Context<'_> {
    fn drop(&mut self) {
        // SAFETY: Modules retain shared ownership after the local context is freed.
        unsafe {
            (self.api.dispose_context)(self.handle);
        }
    }
}

pub struct LlvmKernel {
    program: Program,
    entry: Entry,
    jit: Jit,
    _thread_bound: PhantomData<Rc<()>>,
}

impl LlvmKernel {
    /// Compile a verified numerical program using a trusted LLVM 22 shared library.
    ///
    /// # Errors
    /// Fails explicitly for unsupported platforms, libraries, IR or JIT linking.
    pub fn compile(program: Program, library: &Path) -> Result<Self, EvalError> {
        if !cfg!(target_arch = "x86_64") {
            return Err(EvalError(
                "simulation v0 native backend supports x86-64 hosts".into(),
            ));
        }
        let api = Api::load(library)?;
        let mut handle = ptr::null_mut();
        // SAFETY: Out pointer is valid, null builder requests LLVM defaults.
        api.check(unsafe { (api.create_jit)(&raw mut handle, ptr::null_mut()) })?;
        if handle.is_null() {
            return Err(EvalError("LLVM returned a null LLJIT".into()));
        }
        let jit = Jit { handle, api };
        bind_math(&jit)?;
        let source = emit_llvm(&program);
        // SAFETY: All handles are owned here. Parser consumes the copied buffer;
        // ThreadSafeModule takes module ownership and LLJIT takes that wrapper.
        unsafe {
            let raw_context = (jit.api.new_context)();
            // This context is exclusively owned until the module is published.
            let context = Context {
                handle: (jit.api.wrap_context)(raw_context),
                api: &jit.api,
            };
            let buffer = (jit.api.new_buffer)(
                source.as_ptr().cast(),
                source.len(),
                c"openmat-sim".as_ptr(),
            );
            let mut module = ptr::null_mut();
            let mut message = ptr::null_mut();
            if (jit.api.parse_ir)(raw_context, buffer, &raw mut module, &raw mut message) != 0 {
                return Err(EvalError(jit.api.message(message)));
            }
            // LLVMReturnStatusAction = 2: invalid IR must not abort the host.
            if (jit.api.verify_module)(module, 2, &raw mut message) != 0 {
                (jit.api.dispose_module)(module);
                return Err(EvalError(jit.api.message(message)));
            }
            if !message.is_null() {
                (jit.api.dispose_message)(message);
            }
            (jit.api.set_triple)(module, (jit.api.get_triple)(handle));
            (jit.api.set_layout)(module, (jit.api.get_layout)(handle));
            let options = (jit.api.pass_options)();
            let optimized =
                (jit.api.run_passes)(module, c"default<O2>".as_ptr(), ptr::null_mut(), options);
            (jit.api.dispose_pass_options)(options);
            if !optimized.is_null() {
                (jit.api.dispose_module)(module);
                return Err(jit.api.check(optimized).expect_err("non-null LLVM error"));
            }
            let thread_safe_module = (jit.api.new_module)(module, context.handle);
            jit.api.check((jit.api.add_module)(
                handle,
                (jit.api.get_dylib)(handle),
                thread_safe_module,
            ))?;
        }
        let mut address = 0u64;
        // SAFETY: Lookup writes one executor address; symbol is generated by us.
        jit.api.check(unsafe {
            (jit.api.lookup)(handle, &raw mut address, c"openmat_sim_eval".as_ptr())
        })?;
        let address = usize::try_from(address)
            .map_err(|_| EvalError("JIT address does not fit the host".into()))?;
        if address == 0 {
            return Err(EvalError("LLVM returned a null entry address".into()));
        }
        // SAFETY: x86-64 host, same-process JIT, exact generated C ABI signature.
        let entry = unsafe { std::mem::transmute::<usize, Entry>(address) };
        Ok(Self {
            program,
            entry,
            jit,
            _thread_bound: PhantomData,
        })
    }

    #[must_use]
    pub fn version(&self) -> String {
        let (mut major, mut minor, mut patch) = (0, 0, 0);
        // SAFETY: Valid out pointers; library is owned by this kernel.
        unsafe {
            (self.jit.api.get_version)(&raw mut major, &raw mut minor, &raw mut patch);
        }
        format!("{major}.{minor}.{patch}")
    }

    #[must_use]
    pub fn target_triple(&self) -> String {
        // SAFETY: LLVM owns this NUL-terminated string for the JIT lifetime.
        unsafe {
            CStr::from_ptr((self.jit.api.get_triple)(self.jit.handle))
                .to_string_lossy()
                .into_owned()
        }
    }

    /// Exercise generated validation branches without exposing an unsafe entry pointer.
    ///
    /// # Errors
    /// Fails if native code does not enforce ABI version, lengths and null checks.
    pub fn verify_abi_guards(&self) -> Result<(), EvalError> {
        let input = vec![0.0; self.program.input_count()];
        let mut output = vec![0.0; self.program.output_count()];
        let ni = u64::try_from(input.len())
            .map_err(|_| EvalError("input count is not representable".into()))?;
        let no = u64::try_from(output.len())
            .map_err(|_| EvalError("output count is not representable".into()))?;
        // SAFETY: Invalid version/length branches must return before dereferencing;
        // all non-null buffers are valid. This tests only our generated function.
        unsafe {
            if (self.entry)(
                KERNEL_ABI_VERSION + 1,
                input.as_ptr(),
                ni,
                output.as_mut_ptr(),
                no,
            ) != 1
                || (self.entry)(
                    KERNEL_ABI_VERSION,
                    input.as_ptr(),
                    ni + 1,
                    output.as_mut_ptr(),
                    no,
                ) != 2
                || (self.entry)(
                    KERNEL_ABI_VERSION,
                    input.as_ptr(),
                    ni,
                    output.as_mut_ptr(),
                    no + 1,
                ) != 2
            {
                return Err(EvalError("native ABI version/length guard failed".into()));
            }
            if ni > 0
                && (self.entry)(KERNEL_ABI_VERSION, ptr::null(), ni, output.as_mut_ptr(), no) != 3
            {
                return Err(EvalError("native input pointer guard failed".into()));
            }
            if no > 0
                && (self.entry)(KERNEL_ABI_VERSION, input.as_ptr(), ni, ptr::null_mut(), no) != 3
            {
                return Err(EvalError("native output pointer guard failed".into()));
            }
        }
        Ok(())
    }
}

fn bind_math(jit: &Jit) -> Result<(), EvalError> {
    use ffi::{EvaluatedSymbol, SymbolFlags, SymbolPair};
    extern "C" fn sin(x: f64) -> f64 {
        x.sin()
    }
    extern "C" fn cos(x: f64) -> f64 {
        x.cos()
    }
    extern "C" fn exp(x: f64) -> f64 {
        x.exp()
    }
    extern "C" fn sqrt(x: f64) -> f64 {
        x.sqrt()
    }
    extern "C" fn abs(x: f64) -> f64 {
        x.abs()
    }
    extern "C" fn tanh(x: f64) -> f64 {
        x.tanh()
    }
    let functions: [(&CStr, extern "C" fn(f64) -> f64); 6] = [
        (c"openmat_math_sin", sin),
        (c"openmat_math_cos", cos),
        (c"openmat_math_exp", exp),
        (c"openmat_math_sqrt", sqrt),
        (c"openmat_math_abs", abs),
        (c"openmat_math_tanh", tanh),
    ];
    // SAFETY: Only these six immutable C ABI functions are visible to generated
    // code. ORC consumes the interned names; it copies the temporary pair array.
    unsafe {
        let mut symbols: Vec<SymbolPair> = functions
            .iter()
            .map(|(name, function)| SymbolPair {
                name: (jit.api.intern)(jit.handle, name.as_ptr()),
                symbol: EvaluatedSymbol {
                    address: *function as usize as u64,
                    flags: SymbolFlags {
                        generic: 5,
                        target: 0,
                    },
                },
            })
            .collect();
        let unit = (jit.api.absolute_symbols)(symbols.as_mut_ptr(), symbols.len());
        let error = (jit.api.define)((jit.api.get_dylib)(jit.handle), unit);
        if !error.is_null() {
            (jit.api.dispose_unit)(unit);
        }
        jit.api.check(error)
    }
}

impl Kernel for LlvmKernel {
    fn program(&self) -> &Program {
        &self.program
    }

    fn evaluate(&mut self, inputs: &[f64], outputs: &mut [f64]) -> Result<(), EvalError> {
        if inputs.len() != self.program.input_count()
            || outputs.len() != self.program.output_count()
        {
            return Err(EvalError("numerical kernel buffer length mismatch".into()));
        }
        // SAFETY: Verified program and exact buffer lengths, valid Rust slices,
        // matching C ABI, and the owning LLJIT remains alive for this call.
        let status = unsafe {
            (self.entry)(
                KERNEL_ABI_VERSION,
                inputs.as_ptr(),
                u64::try_from(inputs.len()).expect("bounded inputs"),
                outputs.as_mut_ptr(),
                u64::try_from(outputs.len()).expect("bounded outputs"),
            )
        };
        if status != 0 {
            return Err(EvalError(format!(
                "native kernel returned ABI status {status}"
            )));
        }
        Ok(())
    }
}
