u8_shift = bitshift(255, 1, 'uint8');
i8_shift = bitshift(-1, -1, 'int8');
i8_get = bitget(-1, 8, 'int8');
i8_clear = bitset(-1, 8, 0, 'int8');
i8_or = bitor(-128, 1, 'int8');
i8_xor = bitxor(-1, 127, 'int8');
string_assumed = bitand(3, 1, "uint8");
typed_matching = bitshift(uint8(3), 1, 'uint8');

openmat_result = [ ...
    u8_shift, i8_shift, i8_get, i8_clear, i8_or, i8_xor, string_assumed, ...
    double(typed_matching), ...
    double(strcmp(class(u8_shift), 'double')), ...
    double(strcmp(class(typed_matching), 'uint8')) ...
];
