theta_input = single([0 pi/2; -pi/2 pi]);
rho_input = [1; 2];
[x, y, z_passthrough] = pol2cart(theta_input, rho_input, 'z-pass');
[theta, rho] = cart2pol(x, y);

[azimuth, elevation, radius] = cart2sph([1; 2], [3 4], single(5));
[roundtrip_x, roundtrip_y, roundtrip_z] = sph2cart(azimuth, elevation, radius);

[empty_theta, empty_rho] = cart2pol(zeros(0,3), zeros(1,3));

openmat_result = [ ...
    double(x(:).'), double(y(:).'), ...
    double(theta(:).'), double(rho(:).'), ...
    double(azimuth(:).'), double(elevation(:).'), double(radius(:).'), ...
    double(roundtrip_x(:).'), double(roundtrip_y(:).'), double(roundtrip_z(:).'), ...
    double(strcmp(class(x), 'single')), ...
    double(strcmp(class(azimuth), 'single')), ...
    double(strcmp(z_passthrough, 'z-pass')), ...
    size(empty_theta), size(empty_rho) ...
];
