[r, p, lo, hi] = corrcoef([1 2 4 8], [2 1 3 9]);
[r_alpha, p_alpha, lo_alpha, hi_alpha] = corrcoef( ...
    [1 2 4 8], [2 1 3 9], 'Alpha', 0.1);
[r_pairwise, p_pairwise, lo_pairwise, hi_pairwise] = corrcoef( ...
    [1 NaN; 2 4; 3 8; 4 16], 'Rows', 'pairwise');
r_complex = corrcoef([1+1i 2; 2+3i 5; 4+2i 9]);
[r_single, p_single, lo_single, hi_single] = corrcoef( ...
    single([1 2 4 8]), single([2 1 3 9]));
r_constant = corrcoef([1 1; 1 2; 1 3]);
r_empty_columns = corrcoef(zeros(0, 3));
r_no_variables = corrcoef(zeros(3, 0));
openmat_result = [ ...
    r(:); p(:); lo(:); hi(:); ...
    r_alpha(:); p_alpha(:); lo_alpha(:); hi_alpha(:); ...
    r_pairwise(:); p_pairwise(:); lo_pairwise(:); hi_pairwise(:); ...
    real(r_complex(:)); imag(r_complex(:)); ...
    double(r_single(:)); double(p_single(:)); ...
    double(lo_single(:)); double(hi_single(:)); ...
    r_constant(:); ...
    size(r).'; size(r_pairwise).'; size(r_single).'; ...
    size(r_empty_columns).'; size(r_no_variables).' ...
].';
