expanded = bitand(uint8([1; 2]), uint8([1 2 3]));
scalar_left = bitor(uint16(8), uint16([1 2 4]));
scalar_double = bitxor(int8([-1 7]), 3);
shift_expanded = bitshift(uint8(1), [0 1 2]);
get_expanded = bitget(uint8(3), [1 2 3]);
set_expanded = bitset(uint8(0), [1 2 3], [0 NaN -1]);

empty_binary = bitand(zeros(0,1,'uint8'), zeros(1,3,'uint8'));
empty_shift = bitshift(zeros(0,3,'int16'), 1);
empty_get = bitget(zeros(0,3,'uint32'), 1);
empty_set = bitset(zeros(0,3,'uint64'), 1, 0);

openmat_result = [ ...
    double(expanded(:)).', double(scalar_left), double(scalar_double), ...
    double(shift_expanded), double(get_expanded), double(set_expanded), ...
    size(empty_binary), size(empty_shift), size(empty_get), size(empty_set), ...
    double(strcmp(class(expanded), 'uint8')), ...
    double(strcmp(class(scalar_double), 'int8')), ...
    double(strcmp(class(empty_shift), 'int16')), ...
    double(strcmp(class(empty_get), 'uint32')), ...
    double(strcmp(class(empty_set), 'uint64')) ...
];
