special = complex([NaN Inf 1 2], [0 NaN Inf 0]);
finite_checks = [isnan(special), isinf(special), isfinite(special)];

type_checks = [ ...
    isreal(complex([1 2], [0 0])), ...
    isreal([1 2]), ...
    isnumeric(1), isnumeric(single(1)), isnumeric(uint8(1)), isnumeric(true), isnumeric('a'), ...
    isfloat(1), isfloat(single(1)), isfloat(uint8(1)), ...
    isinteger(1), isinteger(uint8(1)), ...
    islogical(true), islogical(1) ...
];

shape_checks = [ ...
    isscalar([]), isscalar(1), isscalar(string('a')), isscalar({1}), ...
    isvector([]), isvector(zeros(0,1)), isvector(zeros(1,0)), ...
    isvector(ones(1,2)), isvector(ones(2,1)), isvector(ones(2,2)), ...
    ismatrix(zeros(0,0)), ismatrix(ones(2,2,1)), ismatrix(ones(2,2,2)) ...
];

equality_checks = [ ...
    isequal(1, single(1), uint8(1), true), ...
    isequal(complex(1,0), 1), ...
    isequal(0, -0), ...
    isequal(NaN, NaN), ...
    isequaln(NaN, NaN), ...
    isequaln(complex(NaN,1), complex(NaN,1)), ...
    isequaln(complex(NaN,1), complex(1,NaN)), ...
    isequal([], zeros(0,1)), ...
    isequal(zeros(0,2), zeros(0,2)), ...
    isequal({NaN}, {NaN}), ...
    isequaln({NaN}, {NaN}), ...
    isequal(struct('a',1), struct('a',1)), ...
    isequal(struct('a',1), struct('b',1)) ...
];

empty_shape = isnan(zeros(0,3));
openmat_result = [ ...
    finite_checks, type_checks, shape_checks, equality_checks, ...
    isequal(size(empty_shape), [0 3]), islogical(empty_shape) ...
];
