text = fileread('../fixtures/file_io_text.txt');
matrix = readmatrix('../fixtures/file_io_matrix.csv');
single_matrix = readmatrix( ...
    '../fixtures/file_io_matrix.csv', ...
    'Delimiter', ',', ...
    'NumHeaderLines', 1, ...
    'OutputType', 'single');

openmat_result = {text, matrix, single_matrix};
