z = complex([0, 0, 1, -1], [1, -1, 0, 0]);
openmat_result = { ...
    sort(single([2, -1, 0])), ...
    sort([true, false, true]), ...
    sort(int16([2, -1, 0])), ...
    sort('cba'), ...
    sort(z) ...
};
