s = fft(single([1 2 3]));
l = fft(logical([1 0 1]));
x = fft(7, 3);
y = fft(reshape(1:6, [2 3]), 4, 4);
openmat_result = [ ...
    double(strcmp(class(s), 'single')), ...
    double(strcmp(class(l), 'double')), ...
    size(x), size(y), ndims(y), ...
    double(isreal(ifft(fft([1 2 3 4])))) ...
];
