wrapped = [0 3.5 7 NaN 0 4];
unwrapped = unwrap(wrapped);
single_unwrapped = unwrap(single([0 3.5 7]));
by_columns = unwrap([0 4 8; 1 5 9], [], 2);
custom_tolerance = unwrap([0 4], pi, 2);
integer_unwrapped = unwrap(int32([0 4 10 -10]));
character_unwrapped = unwrap(char([0 4 10 100]));
nonfinite = unwrap([0 Inf 4 -Inf 8]);
empty_rows = unwrap(zeros(0, 3));
empty_columns = unwrap(zeros(2, 0));

openmat_result = [ ...
    unwrapped, double(single_unwrapped), by_columns(:).', custom_tolerance, ...
    double(integer_unwrapped), double(character_unwrapped), nonfinite, ...
    double(strcmp(class(single_unwrapped), 'single')), ...
    double(strcmp(class(integer_unwrapped), 'int32')), ...
    double(strcmp(class(character_unwrapped), 'char')), ...
    size(empty_rows), size(empty_columns) ...
];
