eps_empty = eps(zeros(0,3));
inf_empty_single = Inf(2,0,'single');

openmat_result = [ ...
    eps, double(eps('single')), ...
    eps(0), eps(-1), eps(2), double(eps(single(2))), eps(complex(1,2)), ...
    realmin, double(realmin('single')), ...
    realmax, double(realmax('single')), ...
    flintmax, double(flintmax('single')), ...
    Inf, NaN, ...
    double(strcmp(class(eps(single(2))), 'single')), ...
    size(eps_empty), ...
    double(strcmp(class(inf_empty_single), 'single')), size(inf_empty_single) ...
];
