sum_odd = movsum(1:6, 3);
sum_even = movsum(1:6, 4);
sum_pair = movsum(1:6, [2 1]);
mean_even = movmean(1:6, 4);
minimum = movmin([3 2 4 1 5], 3);
maximum = movmax([3 2 4 1 5], 3);
sum_dim = movsum(reshape(1:12, [3 4]), 3, 2);
sum_omit = movsum([1 NaN 3 4], 3, 'omitnan');
minimum_include = movmin([3 NaN 2 4], 3, 'includenan');
sum_discard = movsum(1:6, [2 1], 'Endpoints', 'discard');
mean_fill = movmean(1:6, 4, 'Endpoints', 0);
minimum_fill = movmin([3 2 4 1 5], 3, 'Endpoints', -9);
maximum_fill = movmax([3 2 4 1 5], 3, 'Endpoints', 9);
sum_single = movsum(single([1 2 3]), 3);
mean_complex = movmean(complex([1 2 3], [4 5 6]), 3);
minimum_integer = movmin(uint8([3 1 2]), 3);
sum_logical = movsum(logical([1 0 1]), 3);
empty_sum = movsum(single(zeros(2, 0)), 3);

openmat_result = [ ...
    sum_odd, sum_even, sum_pair, mean_even, minimum, maximum, ...
    sum_dim(:).', sum_omit, minimum_include, sum_discard, mean_fill, ...
    minimum_fill, maximum_fill, double(sum_single), ...
    real(mean_complex), imag(mean_complex), double(minimum_integer), sum_logical, ...
    size(empty_sum), ...
    double(strcmp(class(sum_single), 'single')), ...
    double(strcmp(class(mean_complex), 'double')), ...
    double(strcmp(class(minimum_integer), 'uint8')), ...
    double(strcmp(class(sum_logical), 'double')) ...
];
