a = complex(single([0, 1; 2, 3]), single([1, 0; 0, -1]));
[l, u, lu_p] = lu(a, 'vector');
[q, r, qr_p] = qr(a, 'econ', 'vector');
c = complex(single([4, 1; 1, 3]), single([0, 1; -1, 0]));
[chol_r, chol_status] = chol(c);
lu_residual = a(lu_p, :) - l * u;
qr_residual = a(:, qr_p) - q * r;
chol_residual = c - chol_r' * chol_r;
openmat_result = [ ...
    det(a), ...
    single(norm(double(lu_residual(:)))), ...
    single(norm(double(qr_residual(:)))), ...
    single(norm(double(chol_residual(:)))), ...
    single(chol_status), single(size(q, 2)) ...
];
