minimum = cummin([3 NaN 2 NaN 1]);
minimum_include = cummin([3 NaN 2 NaN 1], 'includenan');
maximum_reverse = cummax([1 3 3 2 3], 'reverse');
minimum_dim = cummin(reshape([3 1 2 4 0 5], [2 3]), 2);
minimum_dim_reverse = cummin(reshape([3 NaN 2 4 0 5], [2 3]), 2, 'reverse', 'omitnan');
minimum_complex = cummin(complex([1 -2 0 2], [1 0 2 0]));
maximum_complex = cummax(complex([1 -2 0 2], [1 0 2 0]));
minimum_single = cummin(single([3 1 2]));
minimum_integer = cummin(uint8([3 1 2]));
minimum_logical = cummin(logical([1 1 0 1]));
empty_minimum = cummin(single(zeros(2, 0)));

openmat_result = [ ...
    minimum, minimum_include, maximum_reverse, ...
    minimum_dim(:).', minimum_dim_reverse(:).', ...
    real(minimum_complex), imag(minimum_complex), ...
    real(maximum_complex), imag(maximum_complex), ...
    double(minimum_single), double(minimum_integer), double(minimum_logical), ...
    size(empty_minimum), ...
    double(strcmp(class(minimum_single), 'single')), ...
    double(strcmp(class(minimum_integer), 'uint8')), ...
    double(strcmp(class(minimum_logical), 'logical')) ...
];
