a = complex(single([1, 2; 0, 3; 2, -1]), single([1, -1; 0, 0.5; -2, 1]));
[u, s, v] = svd(a, 'econ');
residual = a - u * s * v';
u_orthogonality = u' * u - single(eye(2));
v_orthogonality = v' * v - single(eye(2));
openmat_result = [ ...
    single(norm(double(residual(:)))), ...
    single(norm(double(u_orthogonality(:)))), ...
    single(norm(double(v_orthogonality(:)))), ...
    single(isa(u, 'single')), single(isa(s, 'single')), ...
    single(isa(v, 'single')), single(all(imag(s(:)) == 0)), ...
    single(size(s, 1)) ...
];
