a = reshape(1:24, [2 3 4]);
inverse = ipermute(a, [3 1 2]);
rotated = rot90(reshape(1:6, [2 3]), -1);
[shifted, removed] = shiftdim(reshape(1:6, [1 1 2 3]));
inserted = shiftdim(reshape(1:6, [2 3]), -2);
repeated = repelem(reshape(1:6, [2 3]), [1 2], [2 0 1]);
repeated_char = repelem('ab', [2 1]);
blocks_single = blkdiag(single(1), 2);
blocks_integer = blkdiag(1, uint8(2));
blocks_char = blkdiag('ab', 'c');
empty_inverse = ipermute(zeros(0, 2, 3), [3 1 2]);

openmat_result = [ ...
    inverse(:).', rotated(:).', shifted(:).', removed, ...
    size(inserted), repeated(:).', double(repeated_char), ...
    double(blocks_single(:).'), double(blocks_integer(:).'), ...
    double(blocks_char(:).'), size(empty_inverse), ...
    double(strcmp(class(repeated_char), 'char')), ...
    double(strcmp(class(blocks_single), 'single')), ...
    double(strcmp(class(blocks_integer), 'uint8')), ...
    double(strcmp(class(blocks_char), 'char')) ...
];
