mod_values = mod([-5 -0 0 5 Inf NaN], [3 -3 3 -3 3 3]);
rem_values = rem([-5 -0 0 5 Inf NaN], [3 -3 3 -3 3 3]);
mod_zero = mod([-1 0 1], 0);
rem_zero = rem([-1 0 1], 0);
mod_infinite = mod([5 -5 5 -5], [Inf Inf -Inf -Inf]);
hypot_values = hypot([3 Inf NaN], [4 Inf 1]);
hypot_complex = hypot(complex(3,4), 5);
atan2_values = atan2([-0 0 1 -1 Inf Inf NaN], [-1 -1 0 0 Inf -Inf 1]);
single_hypot = hypot(single([3 5]), 4);
single_atan2 = atan2(single([1 0]), single([1 -1]));
empty_result = hypot(zeros(0,3), 1);
broadcast_mod = mod([-5; 5], [3 -3 Inf]);
broadcast_rem = rem([-5; 5], [3 -3 Inf]);
broadcast_hypot = hypot(single([-5; 5]), [3 -3 Inf]);
empty_broadcast = atan2(zeros(0,1), ones(1,3));

openmat_result = [ ...
    mod_values, rem_values, mod_zero, rem_zero, mod_infinite, ...
    hypot_values, hypot_complex, atan2_values, ...
    double(single_hypot), double(single_atan2), ...
    double(strcmp(class(single_hypot), 'single')), ...
    size(empty_result), ...
    double(isequal(broadcast_mod, [1 -2 Inf; 2 -1 5])), ...
    double(isequal(broadcast_rem, [-2 -2 -5; 2 2 5])), ...
    double(isequal(size(broadcast_hypot), [2 3])), ...
    double(strcmp(class(broadcast_hypot), 'single')), ...
    double(isequal(size(empty_broadcast), [0 3])) ...
];
