y = [1 3 6; 2 5 9];
t_default = trapz(y);
t_dim = trapz(y, 2);
t_xy = trapz([0 2 5], [1 3 6]);
ct_default = cumtrapz(y);
ct_dim = cumtrapz([0 2 5], y, 2);
t_single = trapz(single([1 3 6]));
ct_integer = cumtrapz(uint8([1 2 4]));
t_complex = trapz(complex([1 3 6], [2 1 0]));

g_vector = gradient([1 4 9]);
g_nonuniform = gradient([1 4 9], [0 1 3]);
[gx, gy] = gradient(y);
[gxs, gys] = gradient(y, [0 2 5], [0 4]);
[gnx, gny, gnz] = gradient(reshape(1:12, [2 3 2]));
g_single = gradient(single([1 4 9]), 2);
g_integer = gradient(uint8([1 2 4]));
g_complex = gradient(complex([1 4 9], [2 1 0]));
g_empty = gradient(zeros(0,3));

openmat_result = [ ...
    t_default, t_dim.', t_xy, ...
    ct_default(:).', ct_dim(:).', ...
    double(t_single), double(ct_integer), ...
    real(t_complex), imag(t_complex), ...
    g_vector, g_nonuniform, ...
    gx(:).', gy(:).', gxs(:).', gys(:).', ...
    gnx(:).', gny(:).', gnz(:).', ...
    double(g_single), double(g_integer), ...
    real(g_complex), imag(g_complex), size(g_empty), ...
    double(strcmp(class(t_single), 'single')), ...
    double(strcmp(class(ct_integer), 'uint8')), ...
    double(strcmp(class(g_single), 'single')), ...
    double(strcmp(class(g_integer), 'uint8')) ...
];
