angles = [-Inf -720 -630 -540 -450 -360 -270 -180 -90 -45 -0 0 45 90 180 270 360 450 540 630 720 Inf NaN];
sine_values = sind(angles);
cosine_values = cosd(angles);
tangent_values = tand(angles);

inverse_input = [-Inf -2 -1 -0 0 1 2 Inf NaN];
asine_values = asind(inverse_input);
acosine_values = acosd(inverse_input);
atangent_values = atand(inverse_input);

complex_input = complex([0 45 90 -1], [1 -2 3 4]);
complex_sine = sind(complex_input);
complex_cosine = cosd(complex_input);
complex_tangent = tand(complex_input);
complex_asine = asind(complex_input);
complex_acosine = acosd(complex_input);
complex_atangent = atand(complex_input);

atan2_values = atan2d( ...
    [-0 0 -0 0 1 -1 Inf Inf -Inf -Inf NaN], ...
    [-1 -1 1 1 0 0 Inf -Inf Inf -Inf 1]);
atan2_broadcast = atan2d(single([-0; 1]), [-1 0 1]);
single_sine = sind(single([-180 -90 -0 0 90 180]));
empty_result = acosd(zeros(0, 3));

openmat_result = [ ...
    sine_values, cosine_values, tangent_values, ...
    real(asine_values), imag(asine_values), ...
    real(acosine_values), imag(acosine_values), ...
    atangent_values, ...
    real(complex_sine), imag(complex_sine), ...
    real(complex_cosine), imag(complex_cosine), ...
    real(complex_tangent), imag(complex_tangent), ...
    real(complex_asine), imag(complex_asine), ...
    real(complex_acosine), imag(complex_acosine), ...
    real(complex_atangent), imag(complex_atangent), ...
    atan2_values, reshape(double(atan2_broadcast), 1, []), ...
    double(single_sine), ...
    double(strcmp(class(atan2_broadcast), 'single')), ...
    double(strcmp(class(single_sine), 'single')), ...
    size(empty_result) ...
];
