real_input = [-Inf -2 -1 -0 0 1 2 Inf NaN];
sec_values = sec(real_input);
csc_values = csc(real_input);
cot_values = cot(real_input);
sech_values = sech(real_input);
csch_values = csch(real_input);
coth_values = coth(real_input);

asec_values = asec(real_input);
acsc_values = acsc(real_input);
acot_values = acot(real_input);
asech_values = asech(real_input);
acsch_values = acsch(real_input);
acoth_values = acoth(real_input);

complex_input = complex([0 1 -1 2], [1 2 -3 -1]);
complex_sec = sec(complex_input);
complex_csc = csc(complex_input);
complex_cot = cot(complex_input);
complex_sech = sech(complex_input);
complex_csch = csch(complex_input);
complex_coth = coth(complex_input);
complex_asec = asec(complex_input);
complex_acsc = acsc(complex_input);
complex_acot = acot(complex_input);
complex_asech = asech(complex_input);
complex_acsch = acsch(complex_input);
complex_acoth = acoth(complex_input);

single_values = csch(single([-1 -0 0 1]));
single_complex = acoth(complex(single([1 -1]), single([2 -3])));
empty_result = sec(zeros(2, 0, 3));

openmat_result = [ ...
    sec_values, csc_values, cot_values, ...
    sech_values, csch_values, coth_values, ...
    real(asec_values), imag(asec_values), ...
    real(acsc_values), imag(acsc_values), ...
    real(acot_values), imag(acot_values), ...
    real(asech_values), imag(asech_values), ...
    real(acsch_values), imag(acsch_values), ...
    real(acoth_values), imag(acoth_values), ...
    real(complex_sec), imag(complex_sec), ...
    real(complex_csc), imag(complex_csc), ...
    real(complex_cot), imag(complex_cot), ...
    real(complex_sech), imag(complex_sech), ...
    real(complex_csch), imag(complex_csch), ...
    real(complex_coth), imag(complex_coth), ...
    real(complex_asec), imag(complex_asec), ...
    real(complex_acsc), imag(complex_acsc), ...
    real(complex_acot), imag(complex_acot), ...
    real(complex_asech), imag(complex_asech), ...
    real(complex_acsch), imag(complex_acsch), ...
    real(complex_acoth), imag(complex_acoth), ...
    double(single_values), ...
    double(real(single_complex)), double(imag(single_complex)), ...
    double(strcmp(class(single_values), 'single')), ...
    double(strcmp(class(single_complex), 'single')), ...
    size(empty_result) ...
];
