z_single = zeros(2, 3, 'single');
z_complex = zeros(1, 2, 'like', single(1 + 2i));
o_uint = ones(2, 'uint16');
e_logical = eye(2, 3, 'logical');
t = true([1 2]);
f = false(2, 1);

constructor_checks = [ ...
    isa(z_single, 'single'), isequal(size(z_single), [2 3]), ...
    ~isreal(z_complex), isequal(size(z_complex), [1 2]), ...
    isa(o_uint, 'uint16'), isequal(size(o_uint), [2 2]), ...
    islogical(e_logical), isequal(e_logical, logical([1 0 0; 0 1 0])), ...
    islogical(t), isequal(size(t), [1 2]), ...
    islogical(f), isequal(size(f), [2 1]) ...
];

type_checks = [ ...
    ischar('x'), isstring(string('x')), iscell({1}), isstruct(struct()), ...
    isobject(table(1)), ~isobject(1) ...
];

shape_checks = [ ...
    isrow(zeros(1, 0)), iscolumn(zeros(0, 1)), ...
    ~isrow([]), ~iscolumn([]) ...
];

constant_checks = [ ...
    isa(i, 'double'), ~isreal(i), isequal(i, j), ...
    isequal(i, complex(0, 1)), islogical(true), islogical(false) ...
];

openmat_result = [constructor_checks, type_checks, shape_checks, constant_checks];
