a = [1 2; 3 4];
[root_three, alpha, condition] = sqrtm(a);
[root_two, residual] = sqrtm(a);
openmat_result = [ ...
    norm(root_three - root_two, 1), ...
    alpha, condition, residual, ...
    norm(root_two * root_two - a, 1) / norm(a, 1) ...
];
