a = reshape([1 1 2 2 3 3 4 4], 2, 2, 2);
[m_vec, f_vec, c_vec] = mode(a, [1 2]);
[m_tie, f_tie, c_tie] = mode([3 1 3 1]);
[m_nan, f_nan, c_nan] = mode([NaN NaN 1]);
[m_single, f_single, c_single] = mode(single(zeros(0, 3)));
[m_integer, f_integer, c_integer] = mode(int8([2 1 1]));
[m_char, f_char, c_char] = mode('baab');
openmat_result = { ...
    m_vec, f_vec, c_vec, ...
    m_tie, f_tie, c_tie, ...
    m_nan, f_nan, c_nan, ...
    m_single, f_single, c_single, ...
    m_integer, f_integer, c_integer, ...
    m_char, f_char, c_char ...
};
