A = sparse([2 1 2 3 3], [1 1 1 2 2], [4 5 -4 Inf -Inf], 3, 2);
L = sparse(logical([0 1; 1 0]));
C = sparse([1 2], [2 1], [1 + 2i, 3 - 4i], 2, 2);
[find_i, find_j, find_v] = find(C, 1, 'last');
empty_rows = sparse([], [], [], 0, 3);
empty_columns = sparse([], [], [], 3, 0);
reserved = spalloc(4, 5, 9);
logical_duplicates = sparse( ...
    [1 1 1], [1 1 1], logical([false true false]), 2, 2 ...
);
ordered_sum = sparse([1 1 1], [1 1 1], [1e16 -1e16 1], 1, 1);
cancelled_sum = sparse([1 1 1], [1 1 1], [1e16 1 -1e16], 1, 1);
empty_find = find(sparse(0, 0));

openmat_result = [ ...
    isequaln(full(A), [5 0; 0 0; 0 NaN]), ...
    nnz(A) == 2, ...
    isequaln(nonzeros(A), [5; NaN]), ...
    issparse(A), ...
    isequal(full(L), logical([0 1; 1 0])), ...
    islogical(nonzeros(L)), ...
    issparse(spones(L)), ...
    isequal(full(spones(L)), [0 1; 1 0]), ...
    issparse(C.'), ...
    isequal(full(C.'), [0 3 - 4i; 1 + 2i 0]), ...
    isequal(full(C'), [0 3 + 4i; 1 - 2i 0]), ...
    issparse(C(1, 2)), ...
    isequal(full(C(1, 2)), 1 + 2i), ...
    isequal(find_i, 1), ...
    isequal(find_j, 2), ...
    isequal(find_v, 1 + 2i), ...
    issparse(speye(2, 4)), ...
    isequal(full(speye(2, 4)), [1 0 0 0; 0 1 0 0]), ...
    isequal(size(empty_rows), [0 3]), ...
    isequal(size(empty_columns), [3 0]), ...
    isequal(size(reserved), [4 5]), ...
    nnz(reserved) == 0, ...
    issparse(reserved), ...
    issparse(logical_duplicates), ...
    islogical(logical_duplicates), ...
    isequal(full(logical_duplicates), logical([1 0; 0 0])), ...
    isequal(full(ordered_sum), 1), ...
    nnz(cancelled_sum) == 0, ...
    isequal(size(empty_find), [0 0]), ...
    isequal(find(A, Inf), find(A)) ...
];
