s = single([1 2; 3 4]);
openmat_result = [string(class(inv(s))), string(class(pinv(s))), ...
    string(class(trace(s))), ...
    string(class(cross(single([1 0 0]), [0 1 0]))), ...
    string(class(kron([1 2], single([3; 4])))), ...
    string(class(cross(uint8([255 0 0]), uint8([0 2 0])))), ...
    string(class(kron(int16([1 2]), int16([3; 4])))), ...
    string(class(trace(int16([1 2; 3 4]))))];
