source = [3 NaN 1 3 NaN -0 0];
[sorted_values, sorted_indices, sorted_inverse] = unique(source);
[stable_values, stable_indices, stable_inverse] = unique([3 1 3 2], 'stable');
[integer_values, integer_indices] = unique(uint8([3 1 3]));
[complex_values, complex_indices, complex_inverse] = unique(complex([1 1 2 1], [1 -1 0 1]));

[member, location] = ismember([3 NaN 1 0], [1 3 NaN -0]);
[mixed_member, mixed_location] = ismember(single([1 3]), [3 1]);
[complex_member, complex_location] = ismember( ...
    complex([1 1 2], [1 -1 0]), complex([1 2], [1 0]));
empty_member = ismember(zeros(0,3), [1 2]);

openmat_result = [ ...
    sorted_values, sorted_indices.', sorted_inverse.', ...
    stable_values, stable_indices.', stable_inverse.', ...
    double(integer_values), integer_indices.', ...
    real(complex_values), imag(complex_values), complex_indices.', complex_inverse.', ...
    double(member), location, ...
    double(mixed_member), mixed_location, ...
    double(complex_member), complex_location, ...
    size(empty_member), ...
    double(strcmp(class(integer_values), 'uint8')), ...
    double(strcmp(class(member), 'logical')) ...
];
