double_and = bitand([1 2 7], [3 1 4]);
double_or = bitor([1 2 7], [3 1 4]);
double_xor = bitxor([1 2 7], [3 1 4]);
logical_result = bitxor([true false], [false true]);
logical_double = bitand([true false], [1 2]);

i8_result = bitand(int8(-1), int8(3));
u8_result = bitor(uint8(1), uint8(2));
i16_result = bitxor(int16(-1), int16(7));
u16_result = bitand(uint16(65535), uint16(255));
i32_result = bitor(int32(-8), int32(3));
u32_result = bitxor(uint32(9), uint32(3));
i64_result = bitand(int64(-1), int64(15));
u64_result = bitor(uint64(2), uint64(8));
mixed_scalar_double = bitand(uint8([3 7]), 5);

openmat_result = [ ...
    double_and, double_or, double_xor, ...
    double(logical_result), logical_double, ...
    double(i8_result), double(u8_result), double(i16_result), double(u16_result), ...
    double(i32_result), double(u32_result), double(i64_result), double(u64_result), ...
    double(mixed_scalar_double), ...
    double(strcmp(class(i8_result), 'int8')), ...
    double(strcmp(class(u8_result), 'uint8')), ...
    double(strcmp(class(i16_result), 'int16')), ...
    double(strcmp(class(u16_result), 'uint16')), ...
    double(strcmp(class(i32_result), 'int32')), ...
    double(strcmp(class(u32_result), 'uint32')), ...
    double(strcmp(class(i64_result), 'int64')), ...
    double(strcmp(class(u64_result), 'uint64')), ...
    double(strcmp(class(logical_result), 'logical')), ...
    double(strcmp(class(logical_double), 'double')) ...
];
