single_value = conv(single([1 2]), [3 4]);
integer_value = conv(int16([1 2]), int16([3 4]));
logical_value = conv(logical([1 0]), logical([1 1]));
signed_poly = poly(int8([100 100]));
unsigned_poly = poly(uint8([1 2]));
empty_value = conv(zeros(1, 0), [1 2]);
openmat_result = [ ...
    double(strcmp(class(single_value), 'single')), ...
    double(strcmp(class(integer_value), 'double')), ...
    double(strcmp(class(logical_value), 'double')), ...
    double(strcmp(class(signed_poly), 'int8')), ...
    double(strcmp(class(unsigned_poly), 'uint8')), ...
    double(single_value), integer_value, logical_value, ...
    double(signed_poly), double(unsigned_poly), empty_value, size(empty_value) ...
];
