joined_char = fullfile('a', '', 'b', 'c.txt');
joined_string = fullfile("a", ["b" "c"], "d");
[char_path, char_name, char_extension] = fileparts('C:\alpha\beta.tar.gz');
[string_path, string_name, string_extension] = fileparts("C:\alpha\beta.tar.gz");
[empty_path, empty_name, empty_extension] = fileparts('');

openmat_result = { ...
    joined_char, joined_string, ...
    char_path, char_name, char_extension, ...
    string_path, string_name, string_extension, ...
    empty_path, empty_name, empty_extension, ...
    isfile(''), isfolder('')};
