a = [4 1; 0 9];
[root, residual] = sqrtm(a);
negative_root = sqrtm(diag([-1 4]));
rotation_root = sqrtm([0 -1; 1 0]);
single_root = sqrtm(single(a));
[empty_root, empty_residual] = sqrtm([]);
nilpotent_root = sqrtm([0 1; 0 0]);
openmat_result = [ ...
    norm(root - [2 0.2; 0 3], 1), ...
    residual, ...
    norm(negative_root - diag([1i 2]), 1), ...
    norm(double(single_root) - [2 0.2; 0 3], 1), ...
    double(strcmp(class(single_root), 'single')), ...
    double(isnan(empty_residual)), ...
    size(empty_root, 1), size(empty_root, 2), ...
    sum(isinf(nilpotent_root(:))), sum(isnan(nilpotent_root(:))), ...
    norm(rotation_root - [1 -1; 1 1] / sqrt(2), 1) ...
];
