a = reshape(1:6, [2 3]);
d1 = diff(a);
d2 = diff(a, 2);
d_explicit = diff(a, 2, 1);
d_single = diff(single([1 3 2]));
d_uint8 = diff(uint8([1 3 2]));
d_complex = diff(complex([1 3 2], [2 1 0]));

sum_uint8 = cumsum(uint8([250 10]));
product_uint8 = cumprod(uint8([20 20]));
sum_reverse = cumsum([1 2 3], 'reverse');
sum_omit = cumsum([1 NaN 2], 'omitnan');
product_omit = cumprod([2 NaN 3], 'omitnan');
sum_complex = cumsum(complex([1 3 2], [2 1 0]));
empty_diff = diff(zeros(0,3), 2);
empty_sum = cumsum(single(zeros(2,0)));

openmat_result = [ ...
    d1, d2, size(d_explicit), ...
    double(d_single), double(d_uint8), ...
    real(d_complex), imag(d_complex), ...
    double(sum_uint8), double(product_uint8), ...
    sum_reverse, sum_omit, product_omit, ...
    real(sum_complex), imag(sum_complex), ...
    size(empty_diff), size(empty_sum), ...
    double(strcmp(class(d_single), 'single')), ...
    double(strcmp(class(d_uint8), 'uint8')), ...
    double(strcmp(class(sum_uint8), 'uint8')), ...
    double(strcmp(class(empty_sum), 'single')) ...
];
