a = [0, 1; 2, 3];
[l, u, p_matrix] = lu(a);
[folded_l, folded_u] = lu(a);
[vector_l, vector_u, p_vector] = lu(a, 'vector');
matrix_residual = p_matrix * a - l * u;
folded_residual = a - folded_l * folded_u;
vector_residual = a(p_vector, :) - vector_l * vector_u;
openmat_result = [ ...
    norm(matrix_residual(:)), ...
    norm(folded_residual(:)), ...
    norm(vector_residual(:)), ...
    det(a), det(zeros(0, 0)), size(l, 1), size(u, 2) ...
];
