expm1_double = expm1([0 1e-12 -Inf Inf NaN]);
log1p_double = log1p([0 1e-12 -1 -2 Inf NaN]);
complex_values = [ ...
    expm1(complex(1e-12, -2e-12)), ...
    log1p(complex(1e-12, -2e-12)) ...
];
angles = angle([1 -1 0 Inf -Inf NaN complex(0,1) complex(0,-1)]);

single_expm1 = expm1(single([0 1e-4]));
single_log1p = log1p(single([-2 1e-4]));
single_angles = angle(complex(single([-1 0]), single([0 1])));
empty_angles = angle(zeros(0,3));

openmat_result = [ ...
    real(expm1_double), imag(expm1_double), ...
    real(log1p_double), imag(log1p_double), ...
    real(complex_values), imag(complex_values), ...
    angles, ...
    double(single_expm1), ...
    double(real(single_log1p)), double(imag(single_log1p)), ...
    double(single_angles), ...
    double(strcmp(class(single_expm1), 'single')), ...
    double(strcmp(class(single_log1p), 'single')), ...
    double(strcmp(class(single_angles), 'single')), ...
    size(empty_angles) ...
];
