S = single([1 2; 3 4]);
L = logical([1 0; 1 1]);
openmat_result = [string(class(sum(S))), string(class(sum(S, 'double'))), ...
    string(class(sum(uint8([200 100]), 'native'))), string(class(sum(L, 'native'))), ...
    string(class(prod(S))), string(class(prod(S, 'double'))), ...
    string(class(prod(int8([10 20]), 'native'))), string(class(prod(L, 'native')))];
