a = reshape([0, 1, 0, 2], 2, 1, 2);
b = reshape([0, 2, 0, 3], 2, 1, 2);
[row, column, value] = find(b);
openmat_result = { ...
    any(a), ...
    all(a, 2), ...
    any(a, [1, 3]), ...
    all(zeros(0, 3)), ...
    any(zeros(0, 3), 'all'), ...
    row, column, value, ...
    find([1, 2, 0, 3], 2, 'last'), ...
    find(single([0, 2]), 1, 'first') ...
};
