a = single([1, 2; 3, 5]);
singular = diag(single([1, 0]));
empty = single(zeros(0, 3));
rank_value = rank(a);
condition_value = cond(a);
openmat_result = [ ...
    single(rank_value), condition_value, cond(a, 1), cond(a, 'inf'), ...
    cond(a, 'fro'), cond(singular), cond(empty), ...
    single(isa(rank_value, 'double') && isa(condition_value, 'single')) ...
];
