a = [3 NaN 1 3 -0];
b = [1 3 NaN 0];
[ci, iai, ibi] = intersect(a, b);
[cu, iau, ibu] = union(a, b);
[cd, iad] = setdiff(a, b);
[cx, iax, ibx] = setxor(a, b);

[cis, iais, ibis] = intersect([3 1 3 2], [2 3 1 3], 'stable');
[cus, iaus, ibus] = union([3 1 3 2], [4 3 1 4], 'stable');
[cds, iads] = setdiff([3 1 3 2], 3, 'stable');
[cxs, iaxs, ibxs] = setxor([3 1 3 2], [4 3 1 4], 'stable');

[cr, iar, ibr] = union([3 4; 1 2; 3 4], [5 6; 1 2], 'rows', 'sorted');
[cc, iac, ibc] = intersect( ...
    complex([1 1 2 1], [1 -1 0 1]), complex([1 2], [1 0]));
cm = union(uint8([1 2]), [2.5 300 -1]);
ce = union(zeros(0,3), zeros(0,3));

openmat_result = [ ...
    ci, iai.', ibi.', ...
    cu, iau.', ibu.', ...
    cd, iad.', ...
    cx, iax.', ibx.', ...
    cis, iais.', ibis.', ...
    cus, iaus.', ibus.', ...
    cds, iads.', ...
    cxs, iaxs.', ibxs.', ...
    cr(:).', iar.', ibr.', ...
    real(cc), imag(cc), iac.', ibc.', ...
    double(cm), size(ce), ...
    double(strcmp(class(cm), 'uint8')) ...
];
