sorted_default = issorted([1 2 NaN]);
sorted_descend = issorted([NaN 2 1], 'descend');
sorted_dim = issorted([1 3; 2 4], 2);
sorted_rows = issorted([1 3; 2 1; 2 2], 'rows');
sorted_abs = issorted(complex([2 1], [0 5]), 'ComparisonMethod', 'abs');

[mn, imn] = mink([3 NaN 1 3 -Inf Inf], 3);
[mx, imx] = maxk([3 NaN 1 3 -Inf Inf], 3);
[mnd, imnd] = mink([3 1; 4 2], 1, 2);
[mxd, imxd] = maxk(reshape([4 1 3 2 8 5 7 6], [2 2 2]), 1, 3);
[mnt, imnt] = mink([2 1 2 1], 3);
[mxc, imxc] = maxk(complex([1 1 2], [1 -1 0]), 2);
mns = mink(single([3 1 2]), 2);
mni = mink(uint8([3 1 2]), 2);
mne = mink(zeros(0,3), 1);

openmat_result = [ ...
    double([sorted_default sorted_descend sorted_dim sorted_rows sorted_abs]), ...
    mn, imn, mx, imx, ...
    mnd.', imnd.', mxd(:).', imxd(:).', ...
    mnt, imnt, ...
    real(mxc), imag(mxc), imxc, ...
    double(mns), double(mni), size(mne), ...
    double(strcmp(class(mns), 'single')), ...
    double(strcmp(class(mni), 'uint8')) ...
];
