sign_real = sign([-Inf -2 -0 0 2 Inf NaN]);
sign_complex = sign(complex([0 3 Inf NaN], [0 4 1 2]));
asin_values = asin([-2 -1 -0 0 1 2 Inf NaN]);
acos_values = acos([-2 -1 0 1 2]);
atan_values = atan(complex([0 1 Inf NaN], [0 2 1 1]));
hyperbolic = [ ...
    sinh(complex(1,2)), cosh(complex(1,2)), tanh(complex(1,2)), ...
    asinh([-Inf -1 0 1 Inf NaN]), ...
    acosh([-1 0 1 2 Inf NaN]), ...
    atanh([-2 -1 0 1 2 Inf NaN]) ...
];
angles = [ ...
    double(deg2rad(complex(single([0 180]), single([90 -180])))), ...
    rad2deg(complex([0 pi], [pi/2 -pi])) ...
];
empty_double = asin(zeros(0,3));
empty_single = tanh(single(zeros(2,0)));

openmat_result = [ ...
    sign_real, ...
    real(sign_complex), imag(sign_complex), ...
    real(asin_values), imag(asin_values), ...
    real(acos_values), imag(acos_values), ...
    real(atan_values), imag(atan_values), ...
    real(hyperbolic), imag(hyperbolic), ...
    real(angles), imag(angles), ...
    double(strcmp(class(deg2rad(single(1))), 'single')), ...
    size(empty_double), double(strcmp(class(empty_single), 'single')), size(empty_single) ...
];
