a = complex(single([1, 2; 3, 4]), single([0, 1; -1, 0]));
[v, d, w] = eig(a, 'vector');
diagonal = diag(d);
right_residual = a * v - v * diagonal;
left_residual = w' * a - diagonal * w';
trace_error = sum(double(d)) - sum(double(diag(a)));
determinant_error = prod(double(d)) - double(det(a));
openmat_result = [ ...
    single(norm(double(right_residual(:)))), ...
    single(norm(double(left_residual(:)))), ...
    single(abs(trace_error)), single(abs(determinant_error)), ...
    single(isa(v, 'single')), single(isa(d, 'single')), ...
    single(isa(w, 'single')), single(size(d, 2)) ...
];
