a = [1, 2, 4; 3, 5, 7];
[full_u, full_s, full_v] = svd(a);
[econ_u, econ_s, econ_v] = svd(a, 'econ');
[zero_u, zero_s, zero_v] = svd(a, 0);
full_residual = a - full_u * full_s * full_v';
econ_residual = a - econ_u * econ_s * econ_v';
full_u_orthogonality = full_u' * full_u - eye(2);
full_v_orthogonality = full_v' * full_v - eye(3);
openmat_result = [ ...
    norm(full_residual(:)), norm(econ_residual(:)), ...
    norm(full_u_orthogonality(:)), norm(full_v_orthogonality(:)), ...
    size(econ_s, 1), size(econ_v, 2), ...
    size(zero_s, 2), size(zero_v, 2) ...
];
