base_input = [-Inf -8 -3 -1 -0 0 realmin 0.75 1 2 3 8 realmax Inf NaN];
log_values = log2(base_input);
[fractions, exponents] = log2(base_input);

complex_input = complex([0 1 -1 3], [1 -0 0 4]);
complex_log = log2(complex_input);
[complex_fractions, complex_exponents] = log2(complex_input);

single_input = single([-8 -3 -0 0 0.75 1 3 Inf NaN]);
[single_fractions, single_exponents] = log2(single_input);
single_log = log2(single_input);

pow_values = pow2([-Inf -3 -0 0 3 Inf NaN]);
complex_pow = pow2(complex_input);
scaled_values = pow2([3 3 3 3 realmax realmin 1 1], ...
    [-1.9 -0.9 1.9 2.1 1 -1 -1074 -1075]);
scaled_single = pow2(single([0.5 1 3]), [-2 0 2]);

next_values = nextpow2([-Inf -3 -2 -1 -0 0 0.5 1 2 3 realmax Inf NaN]);
next_complex = nextpow2(complex_input);
next_integer = nextpow2(int8([-128 -3 -2 -1 0 1 2 3 127]));
next_logical = nextpow2(logical([0 1]));
empty_log = log2(zeros(0, 2));
empty_pow = pow2(single(zeros(3, 0)));

openmat_result = [ ...
    real(log_values), imag(log_values), fractions, exponents, ...
    real(complex_log), imag(complex_log), ...
    complex_fractions, complex_exponents, ...
    double(real(single_log)), double(imag(single_log)), ...
    double(single_fractions), double(single_exponents), ...
    pow_values, real(complex_pow), imag(complex_pow), ...
    scaled_values, double(scaled_single), ...
    next_values, next_complex, double(next_integer), next_logical, ...
    double(strcmp(class(single_log), 'single')), ...
    double(strcmp(class(single_fractions), 'single')), ...
    double(strcmp(class(scaled_single), 'single')), ...
    double(strcmp(class(next_integer), 'int8')), ...
    size(empty_log), size(empty_pow) ...
];
