left = OpenMatBinaryOperatorProbe(7);
right = OpenMatBinaryOperatorProbe(5);
objects = [left right];

openmat_result = [ ...
    left + right, ...
    left - right, ...
    left * right, ...
    left .* right, ...
    left / right, ...
    left \ right, ...
    left ./ right, ...
    left .\ right, ...
    left ^ right, ...
    left .^ right, ...
    double(left == right), ...
    double(left ~= right), ...
    double(left < right), ...
    double(left <= right), ...
    double(left > right), ...
    double(left >= right), ...
    objects - right, ...
    3 - left ...
];
