object = OpenMatDerivedNumber(4);
openmat_result = [strcmp(class(object), 'OpenMatDerivedNumber'), ...
    isa(object, 'OpenMatDerivedNumber'), ...
    isa(object, 'OpenMatBaseNumber'), isa(object, 'handle'), ...
    isobject(object), isobject(4)];
