named = evalc('1 + 2');
displayed = evalc('disp(''hi'')');
quiet = evalc('x = 5;');
[expression_capture, expression_value] = evalc('4 + 5');

fallback_display = evalc('openmat_missing_evalc', 'disp(''fallback'')');
[fallback_capture, fallback_value] = evalc('openmat_missing_evalc_value', '6 + 5');
successful = evalc('6 + 1', 42);

format compact;
compact = evalc('1 + 2');
format default;

nested = evalc( ...
    'inner = evalc(''disp(''''hidden'''')''); disp(''shown'')');
evalc_handle = @evalc;
handle_capture = evalc_handle('disp(''handle'')');
feval_capture = feval('evalc', 'disp(''feval'')');

named_expected = char([10, double('ans ='), 10, 10, double('     3'), 10, 10]);
successful_expected = char([10, double('ans ='), 10, 10, double('     7'), 10, 10]);
compact_expected = char([double('ans ='), 10, double('     3'), 10]);

openmat_result = isequal(named, named_expected) ...
    && isequal(displayed, char([double('hi'), 10])) ...
    && isempty(quiet) ...
    && x == 5 ...
    && isempty(expression_capture) ...
    && expression_value == 9 ...
    && isequal(fallback_display, char([double('fallback'), 10])) ...
    && isempty(fallback_capture) ...
    && fallback_value == 11 ...
    && isequal(successful, successful_expected) ...
    && isequal(compact, compact_expected) ...
    && isequal(nested, char([double('shown'), 10])) ...
    && isequal(handle_capture, char([double('handle'), 10])) ...
    && isequal(feval_capture, char([double('feval'), 10]));
