h = str2func('sin');
a = feval(h, pi / 2);
b = feval('cos', 0);
c = feval("sqrt", 9);
local_handle = str2func('openmat_dynamic_local');
d = feval(local_handle, 5);
e = feval(@(x, y) x + y, 2, 3);
[m, n] = feval(@size, ones(2, 3));
method_object = OpenMatBaseNumber(4);
method_by_name = feval('score', method_object);
method_by_handle = feval(@score, method_object);
binary_method_object = OpenMatBinaryOperatorProbe(7);
method_object_second = feval('plus', 1, binary_method_object);
method_handle_object_second = feval(@plus, 1, binary_method_object);

missing = @openmat_missing_dynamic_target;
caught = false;
try
    feval(missing);
catch
    caught = true;
end

openmat_result = abs(a - 1) < eps ...
    && abs(b - 1) < eps ...
    && c == 3 ...
    && d == 15 ...
    && e == 5 ...
    && m == 2 && n == 3 ...
    && method_by_name == 4 ...
    && method_by_handle == 4 ...
    && method_object_second == 1 ...
    && method_handle_object_second == 1 ...
    && strcmp(func2str(h), 'sin') ...
    && strcmp(func2str(local_handle), 'openmat_dynamic_local') ...
    && strcmp(func2str(missing), 'openmat_missing_dynamic_target') ...
    && caught;

function result = openmat_dynamic_local(value)
result = value + 10;
end
