figure_handle = figure();
surface_handle = surf([1 2 1; 2 5 2; 1 2 1]);
axes_handle = gca();

x_data = get(surface_handle, 'XData');
y_data = get(surface_handle, 'YData');
z_data = get(surface_handle, 'ZData');
c_data = get(surface_handle, 'CData');
view_value = get(axes_handle, 'View');
z_limits = get(axes_handle, 'ZLim');
c_limits = get(axes_handle, 'CLim');

openmat_result = [ ...
    double(strcmp(class(surface_handle), 'matlab.graphics.chart.primitive.Surface')), ...
    size(x_data), size(y_data), size(z_data), ...
    x_data, y_data.', z_data(:).', c_data(:).', ...
    view_value, z_limits, c_limits, ...
    double(strcmp(get(surface_handle, 'FaceColor'), 'flat')), ...
    double(all(get(surface_handle, 'EdgeColor') == [0 0 0])), ...
    get(surface_handle, 'LineWidth'), ...
    double(strcmp(get(surface_handle, 'CDataMapping'), 'scaled')), ...
    get(surface_handle, 'FaceAlpha'), ...
    double(strcmp(get(axes_handle, 'Projection'), 'orthographic')), ...
    double(strcmp(get(axes_handle, 'Box'), 'off')), ...
    double(strcmp(get(surface_handle, 'LineStyle'), '-')), ...
    double(strcmp(get(axes_handle, 'XGrid'), 'on')), ...
    double(strcmp(get(axes_handle, 'YGrid'), 'on')), ...
    double(strcmp(get(axes_handle, 'ZGrid'), 'on')) ...
];
close(figure_handle);
