figure_handle = figure();
line_handle = plot3([1 2 3], [4 5 6], [7 8 10]);
axes_handle = gca();

openmat_result = [ ...
    double(strcmp(class(line_handle), 'matlab.graphics.chart.primitive.Line')), ...
    get(line_handle, 'XData'), ...
    get(line_handle, 'YData'), ...
    get(line_handle, 'ZData'), ...
    get(axes_handle, 'View'), ...
    get(axes_handle, 'XLim'), ...
    get(axes_handle, 'YLim'), ...
    get(axes_handle, 'ZLim'), ...
    double(strcmp(get(axes_handle, 'Projection'), 'orthographic')), ...
    double(strcmp(get(line_handle, 'LineStyle'), '-')), ...
    double(strcmp(get(line_handle, 'Marker'), 'none')), ...
    get(line_handle, 'LineWidth'), ...
    get(line_handle, 'MarkerSize') ...
];
close(figure_handle);
