figure_handle = figure();
line_handle = plot(1:3, [3, 1, 2]);

set(line_handle, 'cOlOr', [0.2, 0.4, 0.6]);
set(line_handle, 'lInEwId', 3.25);
set(line_handle, 'LiNeStY', '-.');
set(line_handle, 'mArKeR', 'x');
set(line_handle, 'MaRkErSi', 11);

openmat_result = { ...
    get(line_handle, 'COLOR'), ...
    get(line_handle, 'linewidth'), ...
    get(line_handle, 'LINESTYLE'), ...
    get(line_handle, 'marker'), ...
    get(line_handle, 'MARKERSIZE') ...
};
close(figure_handle);
