figure_handle = figure();
axes_handle = gca();
plot(axes_handle, 0:10, 0:10);
xlim(axes_handle, [0, 10]);

set(axes_handle, 'XTick', [0, 5, 10]);
set(axes_handle, 'XTickLabel', {'A', 'B'});
manual_before = { ...
    get(axes_handle, 'XTick'), ...
    get(axes_handle, 'XTickMode'), ...
    get(axes_handle, 'XTickLabel'), ...
    get(axes_handle, 'XTickLabelMode') ...
};

xlim(axes_handle, [0, 20]);
manual_after_limit = { ...
    get(axes_handle, 'XTick'), ...
    get(axes_handle, 'XTickLabel') ...
};
set(axes_handle, 'XTickMode', 'auto');
auto_ticks_manual_labels = { ...
    get(axes_handle, 'XTick'), ...
    get(axes_handle, 'XTickMode'), ...
    get(axes_handle, 'XTickLabel'), ...
    get(axes_handle, 'XTickLabelMode') ...
};

xticks(axes_handle, [1, 3, 7]);
shortcut_ticks = xticks(axes_handle);
xticklabels(axes_handle, {'u', 'v', 'w'});
shortcut_labels = xticklabels(axes_handle);
tick_mode = xticks(axes_handle, 'mode');
label_mode = xticklabels(axes_handle, 'mode');

openmat_result = { ...
    manual_before, manual_after_limit, auto_ticks_manual_labels, ...
    shortcut_ticks, shortcut_labels, tick_mode, label_mode ...
};
close(figure_handle);
