figure_handle = figure();
axes_handle = gca();
plot(axes_handle, 1:3, [1, 2, 3]);
hold(axes_handle, 'on');
plot(axes_handle, 1:3, [3, 2, 1]);

title_handle = title(axes_handle, '$x$', 'Interpreter', 'latex');
xlabel_handle = xlabel(axes_handle, '$f(x)$', 'Interpreter', 'none');
ylabel_handle = ylabel(axes_handle, 'value', 'Interpreter', 'tex');
legend_handle = legend(axes_handle, ...
    '$first$', '$second$', ...
    'Interpreter', 'latex', ...
    'Location', 'best');

openmat_result = { ...
    get(title_handle, 'Interpreter'), ...
    get(xlabel_handle, 'Interpreter'), ...
    get(ylabel_handle, 'Interpreter'), ...
    get(legend_handle, 'String'), ...
    get(legend_handle, 'Interpreter'), ...
    get(legend_handle, 'Location') ...
};
close(figure_handle);
