figure_handle = figure();
axes_handle = gca();
line_handle = plot(axes_handle, 1:3, [2, 4, 3]);
children_before = numel(get(axes_handle, 'Children'));

title_handle = title(axes_handle, 'Main Title', ...
    'Color', [0.1, 0.2, 0.3], 'FontSize', 14);
xlabel_handle = xlabel(axes_handle, 'Horizontal Axis');
ylabel_handle = ylabel(axes_handle, 'Vertical Axis');
children_after = numel(get(axes_handle, 'Children'));

openmat_result = { ...
    class(title_handle), ...
    class(xlabel_handle), ...
    class(ylabel_handle), ...
    [title_handle.Parent == axes_handle, ...
        xlabel_handle.Parent == axes_handle, ...
        ylabel_handle.Parent == axes_handle], ...
    get(title_handle, 'String'), ...
    get(xlabel_handle, 'String'), ...
    get(ylabel_handle, 'String'), ...
    get(title_handle, 'Color'), ...
    get(title_handle, 'FontSize'), ...
    [children_before, children_after, isgraphics(line_handle)] ...
};
close(figure_handle);
openmat_result{end + 1} = [ ...
    isgraphics(title_handle), ...
    isgraphics(xlabel_handle), ...
    isgraphics(ylabel_handle) ...
];
