figure_handle = figure();
axes_handle = gca();
first_line = plot(axes_handle, 1:3, [1, 2, 3]);
hold(axes_handle, 'on');
second_line = plot(axes_handle, 1:3, [3, 2, 1]);
valid_while_held = [isgraphics(first_line), isgraphics(second_line)];

hold(axes_handle, 'off');
replacement_line = plot(axes_handle, 1:3, [2, 2, 2]);
valid_after_replace = [ ...
    isgraphics(first_line), ...
    isgraphics(second_line), ...
    isgraphics(replacement_line) ...
];
child_count = numel(get(axes_handle, 'Children'));
color_index = get(axes_handle, 'ColorOrderIndex');
close(figure_handle);
valid_after_close = isgraphics(replacement_line);

openmat_result = [ ...
    valid_while_held, ...
    valid_after_replace, ...
    child_count, ...
    color_index, ...
    valid_after_close ...
];
