figure_handle = figure();
scatter_handle = scatter(1:3, [4, 6, 5], 36, [0.25, 0.5, 0.75], 'd');

openmat_result = { ...
    class(scatter_handle), ...
    size(scatter_handle), ...
    get(scatter_handle, 'SizeData'), ...
    get(scatter_handle, 'CData'), ...
    get(scatter_handle, 'Marker') ...
};
close(figure_handle);
