figure_handle = figure();
surface_handle = mesh([1 3; 2 4]);

openmat_result = [ ...
    double(strcmp(class(surface_handle), 'matlab.graphics.chart.primitive.Surface')), ...
    double(all(get(surface_handle, 'FaceColor') == [1 1 1])), ...
    get(surface_handle, 'LineWidth'), ...
    double(strcmp(get(surface_handle, 'EdgeColor'), 'flat')), ...
    double(strcmp(get(surface_handle, 'CDataMapping'), 'scaled')), ...
    get(surface_handle, 'FaceAlpha'), ...
    double(all(get(gca(), 'View') == [-37.5 30])) ...
];
close(figure_handle);
