figure_handle = figure();
surf([1 2 1; 2 5 2; 1 2 1]);
axes_handle = gca();

axis equal;
equal_daspect = get(axes_handle, 'DataAspectRatio');
equal_pbaspect = get(axes_handle, 'PlotBoxAspectRatio');
equal_modes = [ ...
    strcmp(get(axes_handle, 'DataAspectRatioMode'), 'manual'), ...
    strcmp(get(axes_handle, 'PlotBoxAspectRatioMode'), 'auto') ...
];

daspect([1 2 3]);
pbaspect([2 1 1]);
manual_daspect = get(axes_handle, 'DataAspectRatio');
manual_pbaspect = get(axes_handle, 'PlotBoxAspectRatio');
manual_modes = [ ...
    strcmp(get(axes_handle, 'DataAspectRatioMode'), 'manual'), ...
    strcmp(get(axes_handle, 'PlotBoxAspectRatioMode'), 'manual') ...
];

openmat_result = [ ...
    equal_daspect, equal_pbaspect, double(equal_modes), ...
    manual_daspect, manual_pbaspect, double(manual_modes) ...
];
close(figure_handle);
