figure_handle = figure();
surf([1 2; 3 4]);
view(45, 30);
zlim([0 10]);
label_handle = zlabel('Height');
[azimuth, elevation] = view();

openmat_result = [ ...
    azimuth, elevation, zlim(), ...
    double(strcmp(get(gca(), 'ZLimMode'), 'manual')), ...
    double(strcmp(class(label_handle), 'matlab.graphics.primitive.Text')), ...
    double(strcmp(get(label_handle, 'String'), 'Height')) ...
];
close(figure_handle);
