figure_handle = figure();
axes_handle = gca();
defaults = { ...
    get(axes_handle, 'FontSize'), ...
    get(axes_handle, 'LineWidth'), ...
    char(get(axes_handle, 'Box')), ...
    get(axes_handle, 'TickLabelInterpreter') ...
};

set(axes_handle, ...
    'FontSize', 12, ...
    'LineWidth', 1.25, ...
    'Box', 'on', ...
    'TickLabelInterpreter', 'latex');
styled = { ...
    get(axes_handle, 'FontSize'), ...
    get(axes_handle, 'LineWidth'), ...
    char(get(axes_handle, 'Box')), ...
    get(axes_handle, 'TickLabelInterpreter') ...
};

box(axes_handle);
toggled = char(get(axes_handle, 'Box'));
box(axes_handle, 'on');
explicit_on = char(get(axes_handle, 'Box'));

openmat_result = {defaults, styled, toggled, explicit_on};
close(figure_handle);
