figure_handle = figure();
line_handle = plot(1:3, [4, 5, 6], 'm--s', ...
    'LineWidth', 1.75, 'MarkerSize', 7);

openmat_result = { ...
    class(line_handle), ...
    size(line_handle), ...
    get(line_handle, 'Color'), ...
    get(line_handle, 'LineStyle'), ...
    get(line_handle, 'LineWidth'), ...
    get(line_handle, 'Marker'), ...
    get(line_handle, 'MarkerSize') ...
};
close(figure_handle);
