figure_handle = figure();
axes_handle = gca();
first_line = plot(axes_handle, 1:3, [1, 2, 3]);
hold(axes_handle, 'on');
second_line = plot(axes_handle, 1:3, [3, 2, 1]);
legend_handle = legend(axes_handle, {'ascending', 'descending'}, ...
    'Location', 'northwest');
grid(axes_handle, 'on');

openmat_result = { ...
    class(legend_handle), ...
    size(legend_handle), ...
    get(legend_handle, 'String'), ...
    char(get(legend_handle, 'Location')), ...
    [legend_handle.Parent == figure_handle, ...
        numel(get(figure_handle, 'Children')), ...
        numel(get(axes_handle, 'Children'))], ...
    char(get(axes_handle, 'XGrid')), ...
    char(get(axes_handle, 'YGrid')), ...
    char(get(axes_handle, 'ZGrid')), ...
    [isgraphics(first_line), isgraphics(second_line), ...
        isgraphics(legend_handle)] ...
};
close(figure_handle);
openmat_result{end + 1} = isgraphics(legend_handle);
