figure_handle = figure();
fill_handle = fill([0 1 1 0], [0 0 1 1], 'green');
hold on;
fill3_handle = fill3([0 1 0], [0 0 1], [0 1 0], 'blue');
tri = [1 2 3; 1 3 4];
x = [0; 1; 1; 0];
y = [0; 0; 1; 1];
z = [0; 1; 0; 1];
trisurf_handle = trisurf(tri, x, y, z);
trimesh_handle = trimesh(tri, x, y, z);

openmat_result = [ ...
    double(strcmp(class(fill_handle), 'matlab.graphics.primitive.Patch')), ...
    double(strcmp(class(fill3_handle), 'matlab.graphics.primitive.Patch')), ...
    double(strcmp(class(trisurf_handle), 'matlab.graphics.primitive.Patch')), ...
    double(strcmp(class(trimesh_handle), 'matlab.graphics.primitive.Patch')), ...
    double(all(get(fill_handle, 'FaceColor') == [0 1 0])), ...
    double(all(get(fill_handle, 'EdgeColor') == [0 0 0])), ...
    size(get(fill_handle, 'XData')), ...
    double(all(get(fill3_handle, 'FaceColor') == [0 0 1])), ...
    size(get(fill3_handle, 'ZData')), ...
    double(strcmp(get(trisurf_handle, 'FaceColor'), 'flat')), ...
    double(all(get(trisurf_handle, 'EdgeColor') == [0 0 0])), ...
    size(get(trisurf_handle, 'Faces')), size(get(trisurf_handle, 'Vertices')), ...
    double(all(get(trimesh_handle, 'FaceColor') == [1 1 1])), ...
    double(strcmp(get(trimesh_handle, 'EdgeColor'), 'flat')), ...
    size(get(trimesh_handle, 'CData')) ...
];
close(figure_handle);
