figure_handle = figure();
scatter_handle = scatter3([1 2 3], [4 5 6], [7 8 10], 25, [1 0 0], 'filled');
axes_handle = gca();

openmat_result = [ ...
    double(strcmp(class(scatter_handle), 'matlab.graphics.chart.primitive.Scatter')), ...
    get(scatter_handle, 'XData'), ...
    get(scatter_handle, 'YData'), ...
    get(scatter_handle, 'ZData'), ...
    get(scatter_handle, 'SizeData'), ...
    get(scatter_handle, 'CData'), ...
    get(axes_handle, 'View'), ...
    get(axes_handle, 'XLim'), ...
    get(axes_handle, 'YLim'), ...
    get(axes_handle, 'ZLim'), ...
    double(strcmp(get(scatter_handle, 'Marker'), 'o')) ...
];
close(figure_handle);
