figure_handle = figure();
theta = [0, pi/2, pi];
radius = [1, 2, 3];
line_handle = polarplot(theta, radius, 'LineWidth', 2);
axes_handle = gca();

default_state = [ ...
    double(strcmp(class(axes_handle), 'matlab.graphics.axis.PolarAxes')), ...
    double(strcmp(class(line_handle), 'matlab.graphics.chart.primitive.Line')), ...
    get(axes_handle, 'ThetaLim'), ...
    get(axes_handle, 'RLim'), ...
    double(strcmp(get(axes_handle, 'ThetaLimMode'), 'auto')), ...
    double(strcmp(get(axes_handle, 'RLimMode'), 'auto')), ...
    get(line_handle, 'LineWidth'), ...
    get(line_handle, 'ThetaData'), ...
    get(line_handle, 'RData'), ...
    numel(get(line_handle, 'XData')), ...
    numel(get(line_handle, 'YData')) ...
];

thetalim([-90, 90]);
rlim([-1, 2]);
thetaticks([-90, 0, 90]);
rticks([-1, 0, 1, 2]);
thetaticklabels({'west', 'zero'});
rticklabels({'low', 'middle', 'high'});
set(axes_handle, ...
    'ThetaDir', 'clockwise', ...
    'ThetaZeroLocation', 'top', ...
    'RAxisLocation', 45);

manual_state = [ ...
    thetalim(), rlim(), thetaticks(), rticks(), ...
    numel(thetaticklabels()), numel(rticklabels()), ...
    double(strcmp(thetalim('mode'), 'manual')), ...
    double(strcmp(rlim('mode'), 'manual')), ...
    double(strcmp(get(axes_handle, 'ThetaDir'), 'clockwise')), ...
    double(strcmp(get(axes_handle, 'ThetaZeroLocation'), 'top')), ...
    get(axes_handle, 'RAxisLocation') ...
];

openmat_result = [default_state, manual_state];
close(figure_handle);
