figure_handle = figure();
patch_handle = patch([0 1 1 0], [0 0 1 1], 'red');
axes_handle = gca();

x_data = get(patch_handle, 'XData');
y_data = get(patch_handle, 'YData');
z_data = get(patch_handle, 'ZData');
faces = get(patch_handle, 'Faces');
vertices = get(patch_handle, 'Vertices');
face_vertex_cdata = get(patch_handle, 'FaceVertexCData');

openmat_result = [ ...
    double(strcmp(class(patch_handle), 'matlab.graphics.primitive.Patch')), ...
    size(x_data), x_data(:).', size(y_data), y_data(:).', ...
    size(z_data), size(faces), faces(:).', ...
    size(vertices), vertices(:).', size(face_vertex_cdata), ...
    double(all(get(patch_handle, 'FaceColor') == [1 0 0])), ...
    double(all(get(patch_handle, 'EdgeColor') == [0 0 0])), ...
    get(patch_handle, 'FaceAlpha'), get(patch_handle, 'EdgeAlpha'), ...
    get(patch_handle, 'LineWidth'), ...
    double(strcmp(get(patch_handle, 'LineStyle'), '-')), ...
    double(strcmp(get(patch_handle, 'CDataMapping'), 'scaled')), ...
    get(axes_handle, 'View') ...
];
close(figure_handle);
