figure_handle = figure();
patch_handle = patch( ...
    'Faces', [1 2 3; 1 3 4], ...
    'Vertices', [0 0 0; 1 0 0; 1 1 0; 0 1 0], ...
    'FaceVertexCData', [1; 2; 3; 4], ...
    'FaceColor', 'interp');

x_data = get(patch_handle, 'XData');
y_data = get(patch_handle, 'YData');
z_data = get(patch_handle, 'ZData');
c_data = get(patch_handle, 'CData');
faces = get(patch_handle, 'Faces');
vertices = get(patch_handle, 'Vertices');
face_vertex_cdata = get(patch_handle, 'FaceVertexCData');

openmat_result = [ ...
    double(strcmp(class(patch_handle), 'matlab.graphics.primitive.Patch')), ...
    size(x_data), x_data(:).', size(y_data), y_data(:).', ...
    size(z_data), z_data(:).', size(c_data), c_data(:).', ...
    size(faces), faces(:).', ...
    size(vertices), size(face_vertex_cdata), ...
    double(strcmp(get(patch_handle, 'FaceColor'), 'interp')), ...
    double(all(get(patch_handle, 'EdgeColor') == [0 0 0])) ...
];
close(figure_handle);
