[initial_message, initial_identifier] = lasterr;
initial = lasterror;

[old_message, old_identifier] = lasterr('alpha', 'OpenMat:Alpha');
[message, identifier] = lasterr;

replacement.message = 'beta';
replacement.extra = 17;
old_state = lasterror(replacement);
current = lasterror;

lasterr_handle = @lasterr;
[handle_old_message, handle_old_identifier] = ...
    lasterr_handle('gamma', 'OpenMat:Gamma');
handle_state = feval('lasterror');

previous = lasterror(initial);
restored = lasterror;

openmat_result = isempty(initial_message) ...
    && isempty(initial_identifier) ...
    && isempty(initial.message) ...
    && isempty(initial.identifier) ...
    && isequal(size(initial.stack), [0 1]) ...
    && isempty(old_message) ...
    && isempty(old_identifier) ...
    && isequal(message, 'alpha') ...
    && isequal(identifier, 'OpenMat:Alpha') ...
    && isequal(old_state.message, 'alpha') ...
    && isequal(old_state.identifier, 'OpenMat:Alpha') ...
    && isequal(current.message, 'beta') ...
    && isempty(current.identifier) ...
    && isequal(size(current.stack), [0 1]) ...
    && isequal(handle_old_message, 'beta') ...
    && isempty(handle_old_identifier) ...
    && isequal(handle_state.message, 'gamma') ...
    && isequal(handle_state.identifier, 'OpenMat:Gamma') ...
    && isequal(previous.message, 'gamma') ...
    && isequal(previous.identifier, 'OpenMat:Gamma') ...
    && isempty(restored.message) ...
    && isempty(restored.identifier) ...
    && isequal(size(restored.stack), [0 1]);
