jordan = [4 1; 0 4];
power_three_halves = jordan ^ 1.5;
power_half = jordan ^ 0.5;
negative_branch = diag([-1 8]) ^ (1 / 3);
complex_exponent = 0.5 + 0.25i;
complex_power = diag([2 4]) ^ complex_exponent;
expected_complex = diag([ ...
    exp(complex_exponent * log(2)), ...
    exp(complex_exponent * log(4)) ...
]);
integer_base = [1 2; 3 4];
integer_square = integer_base ^ 2;
integer_identity = integer_base ^ 0;
integer_inverse = integer_base ^ -1;
single_power = jordan ^ single(0.5);
empty_power = [] ^ 0.5;
openmat_result = [ ...
    norm(power_three_halves - [8 3; 0 8], 1), ...
    norm(power_half - [2 0.25; 0 2], 1), ...
    norm(negative_branch - diag([0.5 + sqrt(3) / 2 * 1i, 2]), 1), ...
    norm(complex_power - expected_complex, 1), ...
    norm(integer_square - integer_base * integer_base, 1), ...
    norm(integer_identity - eye(2), 1), ...
    norm(integer_base * integer_inverse - eye(2), 1), ...
    double(strcmp(class(single_power), 'single')), ...
    norm(double(single_power) - [2 0.25; 0 2], 1), ...
    size(empty_power, 1) + size(empty_power, 2) ...
];
