A = [1 2; 3 4];
C = complex(A, [0 1; -1 0]);

power_two = A ^ 2;
power_zero = A ^ 0;
power_negative = A ^ -1;
single_power = single(A) ^ 3;
single_exponent = A ^ single(2);
complex_power = C ^ 2;
empty_power = zeros(0,0) ^ 0;

openmat_result = [ ...
    power_two(:).', ...
    power_zero(:).', ...
    power_negative(:).', ...
    double(single_power(:).'), ...
    double(single_exponent(:).'), ...
    real(complex_power(:).'), imag(complex_power(:).'), ...
    double(strcmp(class(single_power), 'single')), ...
    double(strcmp(class(single_exponent), 'single')), ...
    double(strcmp(class(complex_power), 'double')), ...
    size(empty_power) ...
];
