a = [1; 2];
b = [10, 20, 30];
x = reshape(1:6, [2, 1, 3]);
y = reshape(10:10:40, [1, 4]);

openmat_result = { ...
    a + b, ...
    a - b, ...
    a .* b, ...
    a ./ b, ...
    a .\ b, ...
    a .^ b, ...
    a < b, ...
    a == b, ...
    x + y, ...
    single(a) + b, ...
    zeros(0, 1) + ones(1, 3), ...
    'ab' == ['a'; 'b'], ...
    int8([1; 2]) == int8([1, 2, 3]) ...
};
