singular_a = sparse([1, 2; 2, 4]);
singular_b = [1, 2; 2, 5];
lastwarn('');
singular_x = singular_a \ singular_b;
[~, singular_warning_id] = lastwarn();

tall_a = sparse([1, 2; 2, 4; 3, 6]);
tall_b = [1, 0; 2, 1; 3, 0];
lastwarn('');
tall_x = tall_a \ tall_b;
[~, tall_warning_id] = lastwarn();

openmat_result = [ ...
    ~issparse(singular_x), ...
    isequal(size(singular_x), [2, 2]), ...
    all(isnan(singular_x(:, 1))), ...
    isinf(singular_x(1, 2)) && singular_x(1, 2) > 0, ...
    isinf(singular_x(2, 2)) && singular_x(2, 2) < 0, ...
    ~isempty(singular_warning_id), ...
    ~issparse(tall_x), ...
    isequal(size(tall_x), [2, 2]), ...
    norm(tall_x - [1, 1/7; 0, 0], 'fro') < 1e-12, ...
    ~isempty(tall_warning_id) ...
];
