real_a = sparse([1, 0, 1; 0, 1, 1]);
real_b = [1, 2; 2, 3];
lastwarn('');
real_x = real_a \ real_b;
[~, real_warning_id] = lastwarn();

shifted_a = sparse([0, 1, 0; 0, 0, 1]);
shifted_b = [4, 6; 5, 7];
lastwarn('');
shifted_x = shifted_a \ shifted_b;
[~, shifted_warning_id] = lastwarn();

complex_a = sparse([1 + 1i, 0, 1; 0, 2 - 1i, 1]);
complex_expected = [1 + 2i, 2 - 1i; -1 + 0.5i, 3 + 2i; 0, 0];
complex_b = complex_a * complex_expected;
lastwarn('');
complex_x = complex_a \ complex_b;
[~, complex_warning_id] = lastwarn();

openmat_result = [ ...
    ~issparse(real_x), ...
    isequal(size(real_x), [3, 2]), ...
    norm(real_x - [1, 2; 2, 3; 0, 0], 'fro') < 1e-12, ...
    isempty(real_warning_id), ...
    ~issparse(shifted_x), ...
    isequal(size(shifted_x), [3, 2]), ...
    norm(shifted_x - [0, 0; 4, 6; 5, 7], 'fro') < 1e-12, ...
    isempty(shifted_warning_id), ...
    ~issparse(complex_x), ...
    isequal(size(complex_x), [3, 2]), ...
    norm(complex_x - complex_expected, 'fro') < 1e-12, ...
    isempty(complex_warning_id) ...
];
