real_sparse_left = sparse([1, 0, 3; 0, 2, 4]);
real_full_right = [5, 8; 6, 9; 7, 10];
real_left_product = real_sparse_left * real_full_right;

real_full_left = [5, 6, 7; 8, 9, 10];
real_sparse_right = sparse([1, 0; 0, 2; 3, 4]);
real_right_product = real_full_left * real_sparse_right;

complex_sparse = sparse([1 + 1i, 0; 0, 2 - 1i]);
complex_full = [1, -1 + 1i; 2 + 1i, 3 - 2i];
complex_left_product = complex_sparse * complex_full;
complex_right_product = complex_full * complex_sparse;

empty_left_product = sparse([], [], [], 2, 0) * zeros(0, 3);
empty_right_product = zeros(3, 0) * sparse([], [], [], 0, 2);

openmat_result = [ ...
    ~issparse(real_left_product), ...
    isequal(size(real_left_product), [2, 2]), ...
    isequal(real_left_product, [26, 38; 40, 58]), ...
    ~issparse(real_right_product), ...
    isequal(size(real_right_product), [2, 2]), ...
    isequal(real_right_product, [26, 40; 38, 58]), ...
    ~issparse(complex_left_product), ...
    isequal(size(complex_left_product), [2, 2]), ...
    isequal(complex_left_product, [1 + 1i, -2; 5, 4 - 7i]), ...
    ~issparse(complex_right_product), ...
    isequal(size(complex_right_product), [2, 2]), ...
    isequal(complex_right_product, [1 + 1i, -1 + 3i; 1 + 3i, 4 - 7i]), ...
    ~issparse(empty_left_product), ...
    isequal(size(empty_left_product), [2, 3]), ...
    isequal(empty_left_product, zeros(2, 3)), ...
    ~issparse(empty_right_product), ...
    isequal(size(empty_right_product), [3, 2]), ...
    isequal(empty_right_product, zeros(3, 2)) ...
];
