astral_left = char(uint16([120, 55357, 56832, 122]));
astral_right = char(uint16([120, 55357, 56832, 113]));
matched = contains(["Abc"; missing; "x😀z"], ["b", "😀"], ...
    'IgnoreCase', true);
openmat_result = double([ ...
    strcmpi("Ab", "aB"), strcmpi(missing, missing), ...
    strncmp(astral_left, astral_right, 3), ...
    strncmpi('Ab', 'aX', 1), strncmp('a', 'b', -1), ...
    matched.', ...
    startsWith("Abc", ["x", "a"], 'IgnoreCase', true), ...
    endsWith("abc", ["x", "c"]) ...
]);
