texts = {' A ', 'b'; '', '😀 '};
upper_texts = upper(texts);
stripped = strip(texts);
lengths = strlength(texts);
contained = contains(texts, {'a', '😀'}, 'IgnoreCase', true);
openmat_result = [double(strcmpi(texts, {' a ', 'B'; '', '😀 '})), ...
    double(strcmp(upper_texts, {' A ', 'B'; '', '😀 '})), ...
    double(strcmp(stripped, {'A', 'b'; '', '😀'})), ...
    lengths, double(contained), ...
    double(startsWith(texts, {' ', '😀'})), ...
    double(endsWith(texts, {' ', 'b'}))];
