char_matrix = ['aß'; 'éz'];
upper_strings = upper(["aß", missing]);
stripped_strings = strip([" x ", missing]);
trimmed_matrix = strtrim([' a  '; 'bc  ']);
lengths = strlength(["a", missing, "😀"]);
openmat_result = [double([ ...
    strcmp(upper(char_matrix), ['Aß'; 'ÉZ']), ...
    strcmp(upper_strings(1), "ASS"), isnan(strlength(upper_strings(2))), ...
    strcmp(reverse(char(uint16([97, 55357, 56832, 98]))), ...
        char(uint16([98, 56832, 55357, 97]))), ...
    strcmp(strip('  x  '), 'x'), strcmp(stripped_strings(1), "x"), ...
    isnan(strlength(stripped_strings(2))), ...
    strcmp(trimmed_matrix, [' a'; 'bc']), ...
    strcmp(deblank(char(uint16([97, 9, 32, 0]))), 'a') ...
]), strlength(char(uint16([97, 55357, 56832]))), lengths];
