astral_text = char(uint16([97, 55357, 56832, 98, 55357, 56832]));
astral_pattern = char(uint16([55357, 56832]));
positions = strfind(astral_text, astral_pattern);
cell_positions = strfind({'ab', 'ba'}, 'a');
replaced_strings = strrep(["ab", "ac"], "a", ["x", "yz"]);
missing_result = replace(["abc", missing], ["a", "b"], "X");
openmat_result = [positions, cell_positions{1}, cell_positions{2}, double([ ...
    strcmp(strrep('a😀a', 'a', 'xy'), 'xy😀xy'), ...
    strcmp(replaced_strings(1), "xb"), strcmp(replaced_strings(2), "yzc"), ...
    strcmp(erase('abcabc', {'a', 'c'}), 'bb'), ...
    strcmp(replace('abcabc', {'a', 'c'}, {'x', 'yz'}), 'xbyzxbyz'), ...
    strcmp(replace('ab', '', 'x'), 'xaxbx'), ...
    strcmp(missing_result(1), "XXc"), isnan(strlength(missing_result(2))) ...
])];
