source = table([1; 2], {'a'; 'b'}, ...
    'VariableNames', {'A', 'B'});
mutated = source;

mutated.A = [11; 22];
mutated.C = single([3; 4]);
mutated.B = [];
mutated.Properties.VariableNames = {'RenamedA', 'Extra'};

openmat_result = { ...
    source, ...
    mutated, ...
    height(mutated), ...
    width(mutated), ...
    head(mutated, 1), ...
    tail(mutated, 1) ...
};
