scores = [10; 20; 30];
names = {'alpha'; 'beta'; 'gamma'};
T = table(scores, names, 'VariableNames', {'Score', 'Name'});

selected = T([3 1], {'Name', 'Score'});
extracted = T{[2 3], 1};

openmat_result = { ...
    T, ...
    T.Properties.VariableNames, ...
    T.Name, ...
    selected, ...
    extracted ...
};
