modified = readtable( ...
    '../fixtures/table_readtable_inference.csv', ...
    'VariableNamingRule', 'modify', ...
    'TextType', 'string');
preserved = readtable( ...
    '../fixtures/table_readtable_inference.csv', ...
    'VariableNamingRule', 'preserve', ...
    'TextType', 'char');

openmat_result = {modified, preserved};
