[package]
name = "openmat-sim-slx"
license = "AGPL-3.0-only"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
openmat-opc = { path = "../openmat-opc" }
openmat-sim = { path = "../openmat-sim" }
roxmltree.workspace = true
serde.workspace = true

[dev-dependencies]
openmat-sim-llvm = { path = "../openmat-sim-llvm" }
serde_json.workspace = true
zip.workspace = true

[lints]
workspace = true
