[package]
license = "AGPL-3.0-only"
name = "openmat-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
openmat-bytecode = { path = "../openmat-bytecode" }
openmat-hir = { path = "../openmat-hir" }
openmat-source = { path = "../openmat-source" }

[lints]
workspace = true
